---
title       : DiamondEstim  
subtitle    : Developing Data Products - course project
author      : Yoni DAHAN
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
 

## DiamondEstim   
Allows you to estimate the value of your diamond.
Given your stone's characteristics :   
- weight (carat)
- clarity (I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF)   
- color (D, E, F, G, H)
- cut (fair, good, very good, premium, ideal),

DiamondEstim produces an estimated value in USD.

---

## Algorithm   
DiamondEstim uses the *diamonds* data that comes with the R package "ggplot2".   

This data contains the prices and other characteristics of no less than 54,000 round cut diamonds.   

A lasso regularized regression model is built with :   
- price as response   
- weight, color, clarity and cut as predictors

It has a root mean squared error of about USD14.4


--- 
## Price regarding carat and clarity   

```{r echo=TRUE,eval=TRUE}
library(caret);library(ggplot2);data(diamonds)   

qplot(data=diamonds,carat,price,color=clarity)


```

---

## Front-end
In the left side of the page, DiamondEstim asks you to provide the following :   

- weight (from 0.5 to 5ct) ; using a field to enter numbers   
   
   and:

- color, clarity, cut ; using boxes with choices to select from   


In the right side is showed :   

- a summary of the stone's characteristics   
- an estimated value in USD  

-------- 

## Information  
DiamondEstim is available here : [https://yonidahan.shinyapps.io/courseproject_app/]( https://yonidahan.shinyapps.io/courseproject_app/)   

For any information or documentation :   

- dahan.yoni1@gmail.com   

- [ https://yonidahan.shinyapps.io/courseproject_doc/]( https://yonidahan.shinyapps.io/courseproject_doc/)








